[target.x86_64-pc-windows-msvc]
#linker = "clang"
linker = "lld"
rustflags = [
#    "-C",
#    "link-arg=--ld-path=/usr/bin/mold",
    "-Lnative=/home/jack/.xwin/crt/lib/x86_64",
    "-Lnative=/home/jack/.xwin/sdk/lib/um/x86_64",
    "-Lnative=/home/jack/.xwin/sdk/lib/ucrt/x86_64",
    "-Zshare-generics=y"
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Zshare-generics=y"]